//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/jaytek/connectors/black23.yaml
// auto-generated by PinoutLogic.java based on config/boards/jaytek/connectors/blue35.yaml
// auto-generated by PinoutLogic.java based on config/boards/jaytek/connectors/white35.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::F11, // Lowside 1
	Gpio::G10, // Lowside 17
	Gpio::F13, // Lowside 3
	Gpio::G12, // Lowside 19
	Gpio::F15, // Lowside 5
	Gpio::G14, // Lowside 21
	Gpio::G1, // Lowside 7
	Gpio::E12, // Lowside 13
	Gpio::E8, // Lowside 9
	Gpio::E14, // Lowside 15
	Gpio::E10, // Lowside 11
	Gpio::E11, // Lowside 12
	Gpio::F12, // Lowside 2
	Gpio::G11, // Lowside 18
	Gpio::F14, // Lowside 4
	Gpio::G13, // Lowside 20
	Gpio::G0, // Lowside 6
	Gpio::G15, // Lowside 22
	Gpio::E7, // Lowside 8
	Gpio::E13, // Lowside 14
	Gpio::E9, // Lowside 10
	Gpio::E15, // Lowside 16
	Gpio::G6, // Highside 5
	Gpio::G7, // Highside 6
	Gpio::C6, // Highside 8
	Gpio::G8, // Highside 7
	Gpio::G4, // Highside 3
	Gpio::G5, // Highside 4
	Gpio::G2, // Highside 1
	Gpio::G3, // Highside 2
	Gpio::E2, // Ign 1
	Gpio::E3, // Ign 2
	Gpio::E4, // Ign 3
	Gpio::E5, // Ign 4
	Gpio::E6, // Ign 5
	Gpio::C12, // Ign 6
	Gpio::C11, // Ign 7
	Gpio::C10, // Ign 8
	Gpio::F0, // Ign 9
	Gpio::F1, // Ign 10
	Gpio::F2, // Ign 11
	Gpio::F3, // Ign 12
// "Lowside 1",
// "Lowside 17",
// "Lowside 3",
// "Lowside 19",
// "Lowside 5",
// "Lowside 21",
// "Lowside 7",
// "Lowside 13",
// "Lowside 9",
// "Lowside 15",
// "Lowside 11",
// "Lowside 12",
// "Lowside 2",
// "Lowside 18",
// "Lowside 4",
// "Lowside 20",
// "Lowside 6",
// "Lowside 22",
// "Lowside 8",
// "Lowside 14",
// "Lowside 10",
// "Lowside 16",
// "Highside 5",
// "Highside 6",
// "Highside 8",
// "Highside 7",
// "Highside 3",
// "Highside 4",
// "Highside 1",
// "Highside 2",
// "Ign 1",
// "Ign 2",
// "Ign 3",
// "Ign 4",
// "Ign 5",
// "Ign 6",
// "Ign 7",
// "Ign 8",
// "Ign 9",
// "Ign 10",
// "Ign 11",
// "Ign 12",
}
