//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/jaytek/connectors/black23.yaml
// auto-generated by PinoutLogic.java based on config/boards/jaytek/connectors/blue35.yaml
// auto-generated by PinoutLogic.java based on config/boards/jaytek/connectors/white35.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A0: return "Analog Volt 1";
		case Gpio::A1: return "Analog Volt 2";
		case Gpio::A2: return "Analog Volt 3";
		case Gpio::A3: return "Analog Volt 4";
		case Gpio::A4: return "Analog Volt 5";
		case Gpio::A5: return "Analog Volt 6";
		case Gpio::A6: return "Analog Volt 7";
		case Gpio::A7: return "Analog Volt 8";
		case Gpio::B0: return "Analog Volt 11";
		case Gpio::C0: return "Analog Temp 1";
		case Gpio::C1: return "Analog Temp 2";
		case Gpio::C10: return "Ign 8";
		case Gpio::C11: return "Ign 7";
		case Gpio::C12: return "Ign 6";
		case Gpio::C2: return "Analog Temp 3";
		case Gpio::C3: return "Analog Temp 4";
		case Gpio::C4: return "Analog Volt 9";
		case Gpio::C5: return "Analog Volt 10";
		case Gpio::C6: return "Highside 8";
		case Gpio::D10: return "Digital 3";
		case Gpio::D11: return "Digital 4";
		case Gpio::D12: return "Digital 5";
		case Gpio::D13: return "Digital 6";
		case Gpio::D14: return "Digital 7";
		case Gpio::D15: return "Digital 8";
		case Gpio::D8: return "Digital 1";
		case Gpio::D9: return "Digital 2";
		case Gpio::E0: return "VR 1";
		case Gpio::E1: return "VR 2";
		case Gpio::E10: return "Lowside 11";
		case Gpio::E11: return "Lowside 12";
		case Gpio::E12: return "Lowside 13";
		case Gpio::E13: return "Lowside 14";
		case Gpio::E14: return "Lowside 15";
		case Gpio::E15: return "Lowside 16";
		case Gpio::E2: return "Ign 1";
		case Gpio::E3: return "Ign 2";
		case Gpio::E4: return "Ign 3";
		case Gpio::E5: return "Ign 4";
		case Gpio::E6: return "Ign 5";
		case Gpio::E7: return "Lowside 8";
		case Gpio::E8: return "Lowside 9";
		case Gpio::E9: return "Lowside 10";
		case Gpio::F0: return "Ign 9";
		case Gpio::F1: return "Ign 10";
		case Gpio::F11: return "Lowside 1";
		case Gpio::F12: return "Lowside 2";
		case Gpio::F13: return "Lowside 3";
		case Gpio::F14: return "Lowside 4";
		case Gpio::F15: return "Lowside 5";
		case Gpio::F2: return "Ign 11";
		case Gpio::F3: return "Ign 12";
		case Gpio::F6: return "Analog Volt 13";
		case Gpio::F7: return "Analog Volt 14";
		case Gpio::F8: return "Analog Volt 15";
		case Gpio::F9: return "Analog Volt 16";
		case Gpio::G0: return "Lowside 6";
		case Gpio::G1: return "Lowside 7";
		case Gpio::G10: return "Lowside 17";
		case Gpio::G11: return "Lowside 18";
		case Gpio::G12: return "Lowside 19";
		case Gpio::G13: return "Lowside 20";
		case Gpio::G14: return "Lowside 21";
		case Gpio::G15: return "Lowside 22";
		case Gpio::G2: return "Highside 1";
		case Gpio::G3: return "Highside 2";
		case Gpio::G4: return "Highside 3";
		case Gpio::G5: return "Highside 4";
		case Gpio::G6: return "Highside 5";
		case Gpio::G7: return "Highside 6";
		case Gpio::G8: return "Highside 7";
		default: return nullptr;
	}
	return nullptr;
}
